# Generated by Django 3.2.6 on 2021-08-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('author', models.CharField(max_length=30)),
                ('genre', models.CharField(choices=[('fiction', 'Fiction'), ('non-fiction', 'Non-fiction')], default='None', max_length=11)),
                ('length', models.CharField(max_length=15)),
                ('emotional_value', models.TextField(max_length=255)),
                ('review', models.TextField(max_length=1500)),
                ('mark', models.CharField(choices=[('1', 'dislike'), ('2', 'did not like'), ('3', 'neutral'), ('4', 'liked'), ('5', 'loved it')], max_length=1)),
                ('private', models.BooleanField(default=False)),
            ],
        ),
    ]
