# Generated by Django 3.2.6 on 2021-08-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('event_picture', models.URLField()),
                ('description', models.TextField(max_length=800)),
                ('duration', models.DurationField()),
            ],
        ),
    ]
