# Generated by Django 3.2.6 on 2021-08-08 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_event', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='ClubEvents',
        ),
    ]
